# Generated by Django 3.2 on 2023-04-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=5000000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
